#!/bin/sh
dirs=$(find . -type d | grep -v '^.$')
for dir in $dirs; do
	if [ "$(echo $dir | grep 'typo')" ]; then
		files=$(find "$dir" -type f | grep -v '\.out' | grep -v '\.time' | grep '\/_' | grep '.c$')
		for file in $files; do
			echo "time c-spellcheck $file --trie $(echo $file | sed 's/_[^.]*\.//') >$file-trie.out"
			{
				time c-spellcheck "$file" --trie "$(echo "$file" | sed 's/_[^.]*\.//')" >"$file-trie.out"
			} 2>"$file-trie.time"
			{
				time c-spellcheck "$file" --dld "$(echo "$file" | sed 's/_[^.]*\.//')" >"$file-dld.out"
			} 2>"$file-dld.time"
			{
				time c-spellcheck "$file" --gabungan "$(echo "$file" | sed 's/_[^.]*\.//')" >"$file-gabungan.out"
			} 2>"$file-gabungan.time"
		done
	fi
done
