#!/bin/sh
dirs=$(find . -type d | grep -v '^.$' | grep typo)
for dir in $dirs; do
	files=$(find "$dir" -type f | grep -F '.time')
	for file in $files; do
		grep 'real	.m' "$file" | sed 's/^.*m//; s/s//' > "$(echo "$file" | sed 's/time/rtime/')"
	done
done
