#!/bin/sh
content=$(cat output)
i=1
n=$(echo "$content" | wc -l)
# echo 'TP TN FP FN'
# echo 'DLD Trie Gabungan File'
while [ "$i" -lt "$n" ]; do
	file=$(echo "$content" | head -$((i)) | tail -1 | sed 's/-.*:.*//')
	d_TP=$(echo "$content" | head -$((i)) | tail -1 | sed 's/.*:[ 	]*//')
	d_TN=$(echo "$content" | head -$((i + 1)) | tail -1 | sed 's/.*:[ 	]*//')
	d_FP=$(echo "$content" | head -$((i + 2)) | tail -1 | sed 's/.*:[ 	]*//')
	d_FN=$(echo "$content" | head -$((i + 3)) | tail -1 | sed 's/.*:[ 	]*//')
	g_TP=$(echo "$content" | head -$((i + 4)) | tail -1 | sed 's/.*:[ 	]*//')
	g_TN=$(echo "$content" | head -$((i + 5)) | tail -1 | sed 's/.*:[ 	]*//')
	g_FP=$(echo "$content" | head -$((i + 6)) | tail -1 | sed 's/.*:[ 	]*//')
	g_FN=$(echo "$content" | head -$((i + 7)) | tail -1 | sed 's/.*:[ 	]*//')
	t_TP=$(echo "$content" | head -$((i + 8)) | tail -1 | sed 's/.*:[ 	]*//')
	t_TN=$(echo "$content" | head -$((i + 9)) | tail -1 | sed 's/.*:[ 	]*//')
	t_FP=$(echo "$content" | head -$((i + 10)) | tail -1 | sed 's/.*:[ 	]*//')
	t_FN=$(echo "$content" | head -$((i + 11)) | tail -1 | sed 's/.*:[ 	]*//')
	echo "$d_TP	$d_TN	$d_FP	$d_FN	$t_TP	$t_TN	$t_FP	$t_FN	$g_TP	$g_TN	$g_FP	$g_FN	$file"
	i=$((i + 12))
done
